### ISSUE TITLE
Problems with media volume slider

### ISSUE THREAD

**Issue by Warden20** [toneiv/UbikiTouch#154]
When I run the shortcut to change the media volume it doesn't work, the application freezes.
My operating system is Hyperos Android 15.

Either with any personal or default settings does not work.

**Comment by Warden20** [comment]
Is there an update about this?

**Comment by toneiv** [comment]
This should be fixed in version 1.16.4, which is available in the beta channel. I’m closing this ticket; please feel free to reopen it if necessary.

**Comment by Warden20** [comment]
I'm using the latest version of the Play Store (1.16.10) and I'm still having the same problem. Could you please look into i

**Comment by Warden20** [comment]
Can you fix it? I can reopen the issue
